version: "3"
services:
   server:
     image: jakejarvis/hugo-extended
     container_name: hugo-server
     # command: new site /src
     command: server --bind=0.0.0.0 --port=1313  --baseURL=http://localhost --disableFastRender
     volumes:
       - "${PWD}/src:/src"
     ports:
       - "1313:1313"