version: "3"
services:
   server:
     image: klakegg/hugo
     container_name: hugo-server
     command: new site /src
     # command: server
     volumes:
       - "${PWD}/src:/src"
     ports:
       - "1313:1313"