baseURL = 'http://10.0.1.1/' 
languageCode = 'zh-cn'
theme = "JuiceBar"
title = "Allen's Blog"

[params]
author = "allen"
description = "Talk is too cheap,show me code"
authorImage = "/images/avatar.jpg"
paginate = 5 
Title = "Change the world"
content = "I'm Allen, nice to meet you(ˊ˘ˋ*)♡"
imageUrl = "/images/avatar.jpg"

# To add a new social icon 
# More social icons can be found in JuiceBar\layouts\partials\svg.html.
[[params.social]]
name = "Github"
url = "https://github.com/allencaosong"
# [[params.social]]
# name = "telegram"
# url = "https://t.me/Hotjuice"
# [[params.social]]
# name = "twitter"
# url = "https://twitter.com/hotjuicee"
[[params.social]]
name = "email"
url = "caosong199509@163.com"
[[params.social]]
name = "phone"
url = "13220132585"
# [[params.social]]
# name = "instagram"
# url = "your_url"
# [[params.social]]
# name = "mastodon"
# url = "your_url"
# [[params.social]]
# name = "reddit"
# url = "your_url"
# [[params.social]]
# name = "stackoverflow"
# url = "your_url"

[taxonomies]
category = "categories"
tag = "tags"

# To add a new navigation link
[[menu.main]]
name = "关于我"
url = "/about"
[[menu.main]]
name = "文章列表"
url = "/post"
[[menu.main]]
name = "文章分类"
url = "/categories"

# If using the giscus commenting system
#[params.giscus]
#repo = "ENTER REPO HERE"
#repoID = "ENTER REPO ID HERE"
#category = "ENTER CATEGORY NAME HERE"
#categoryID = "ENTER CATEGORY ID HERE"
#mapping = "og:title"
#reactionsEnabled = "1"
#emitMetadata = "0"
#inputPosition = "bottom"
#lang = "en"
#loading = "lazy"

# Used for outputting the documentation (required).
[outputs]
home = ["HTML", "RSS", "JSON"]